name: gophercon
description: A Helm charts for Kubernetes application
version: 0.0.3
home: https://k8s.community/
sources:
  - https://github.com/rumyantseva/gophercon
maintainers:
  - name: Kubernetes Community Authors
    email: k8s.community@gmail.com
engine: gotpl
